inherit_from: .rubocop_todo.yml
require: 
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance
AllCops:
  Exclude:
    - 'db/**/*'
    - 'vendor/bundle/**/*'
Style/Documentation:
  Enabled: false
